QW-Group/ktx

include/g_local.h
include/progs.h
resources/example-configs/ktx/ktx.cfg
src/commands.c
src/vote.c
src/world.c

I could only test this on localhost but it follows nospecs quite closely. Let me know if you want me to clean up the formatting. The whitespace is pretty unbearable.

Vote to allow or disallow teamoverlay

---

src/match.c

Show hit and fired number of cells in end game stats if the player shot any cells at all:

Add End Game LG (Hit/Fire) next to percentage

---

include/progs.h
src/combat.c
src/match.c

(no functional changes in second commit, just resolving merge conflicts)

Add End Game Enemy Weapon Damage Stat

---

src/commands.c
src/race.c
src/world.c

k_race_autorecord set by default
If not recording demo, don't set demoname in .top file
"/race_dl_record_demo x" downloads demo of record #x
Fixed up route names for dmX maps

RACE: minor changes to demo-recording

---

src/match.c

Untested fix for Boomsticker

---

include/g_local.h

Not sure of best way to contact everyone...  
Want to try and get all the servers up to the latest version.  Will create github version, and then do the same for qtv & mvdsv, then try and chase server admins to update.
Anything else that needs to be done?

VERSION: Finish version 1.37

---

src/admin.c
src/stats.c
src/stats_json.c

Adds the average damage taken to die to each player stats report and awards the "Survivor" title for the one who had the highest average.

average damage taken to die; survivor stats; change server status during forcestart giving a chance for players to get ready before they get kicked;

---

src/combat.c

Brazil has always been a bastion of CTF players, let's please them :)

Issue: Runes - Ajuste in Power #64

---

src/maps.c

MAPCYCLE: Simplify map cycle logic

---

tools/cross-compilation/windows-x86.txt

BUILD: add -msse2 -mfpmath=sse to win x86 build

---

src/commands.c

DOCUMENTATION: update fpd url references to a working site

---

src/commands.c
src/items.c

Also replaced the spawn location indicator model (that ugly SPAWN text)
with the lovely wizard from the single player

Make the spawn location visibility a toggle option

---

include/g_consts.h
include/g_local.h
src/client.c
src/combat.c
src/fb_globals.h
src/g_main.c
src/g_userinfo.c
src/race.c
src/spectate.c
src/stats.c
src/stats_json.c
src/vote.c
src/weapons.c

- MINOR: Tidy up functions imported from fbca
2a9c894
- ADMIN: Clear existing votes when become admin
a2eba6a
- ADMINS: Downgrade elected admins on match start
b9170e2
- DMG NOTIFICATIONS: Store in .mvd, send to client in prewar
bed78ab
- PREWAR: Option for non-random pellet distribution in prewar
5cf22c0
- RACE: Store full usercommands in hidden packets
241e773
- STATS: Embed .json stats file in .mvd at match end
01159f9
- STATS: Fix login name in .json stats
e4384db
- WEAPONSTATS: Refresh weaponstats when wpsx toggled
7e74973
- VOTES: add privategame check when checking all
a564aa8

Meag's changes that are not yet in the master:

---

src/admin.c
src/bot_client.c
src/commands.c
src/match.c

Added 'slowready' command that doesn't trigger the idlebot, but ready up the player

---

include/g_local.h
src/client.c
src/commands.c
src/g_utils.c
src/match.c
src/world.c

Added score calculation for the XonXonX modes

Fixed the score calculation for XonXonX modes.

---

Makefile
Makefile.in

default to compiling build-dlbots
run configure command if not yet run

MAKE: default target, run configure

---

.github/workflows/build-all-targets.yml
.github/workflows/build-targets-cmake.yml
tools/cross-cmake/linux-i686.cmake
tools/cross-compilation/linux-aarch64.txt
tools/cross-compilation/linux-i686.txt

Also fixed some little things, based on the recent changes in mvdsv.

Using cmake as build tool

---

src/clan_arena.c
src/client.c

Fixed a few bugs relating to players leaving and rejoining server, and spectators seeing centerprint messages they shouldn't.

CLAN ARENA: bug fixes

---

include/g_local.h
src/client.c
src/match.c
src/world.c

Cosmetic followup of PR#236

---

src/clan_arena.c

https://github.com/QW-Group/ktx/commit/41ba4c9567a3d5d9c63e40d7300d8490bde17170 caught my attention.
Output shouldn't have changed, but please verify - I haven't played a real wipeout game to compare with yet.

sprintf+strcat -> G_bprint's own format strings

---

include/g_local.h
src/g_utils.c

I'm just finding them going through the code. Hope this doesn't come over as pedantic.

Typo fixes

---

include/g_local.h
include/g_syscalls.h
src/g_main.c
src/g_spawn.c
src/g_syscalls.c

This opens up for static transparent brushes in maps.

SPAWN: Expose alpha entity field to server.

---

resources/example-configs/ktx/race/routes/ztricks2.route

race: added ztricks2 route by Us3

---

src/stats.c

Changed endgame stats to show rls fired

---

resources/example-configs/ktx/race/routes/e1m2.route

race: added e1m2 route (vvd)

---

src/stats.c

New go on adding amount of rockets fired to endgame stats

---

src/commands.c

PAUSE: format string injections are too exciting

---

include/g_local.h
include/progs.h
resources/example-configs/ktx/ktx.cfg
src/commands.c
src/vote.c
src/world.c

The command adds a new election option that allows players to vote on a color change for other players.
Usage:
suggestcolor 12 4 ToT_Oddjob ToT_Psycho_Dad ToT_SlabbY
Feature requested by bps

Add suggestcolor

---

resources/example-configs/ktx/bots/maps/qobblestone.bot

A bot file for map qobblestone (not perfect but better than nothing :p).
//Åke Vader

Add bot support for qobblestone map

---

resources/example-configs/ktx/bots/maps/aztek.bot
resources/example-configs/ktx/bots/maps/forsaken.bot
resources/example-configs/ktx/bots/maps/obsidian.bot
resources/example-configs/ktx/bots/maps/phantombase.bot
resources/example-configs/ktx/bots/maps/rocka.bot

Bot waypoints for Aztek, Forsaken, Obsidian, Phantombase and Rocka.

New bot map support

---

resources/example-configs/ktx/bots/maps/obsidian.bot

Obsidian bot waypoint fixes after feedback from Zigg.

Obsidian bot file fixes

---

src/bot_commands.c

Due to a bug in mvdsv, this will not work unless this https://github.com/QW-Group/mvdsv/pull/177 is merged.

Add bot skill to userinfo
