src/match.c
This adds the good teamplay end game statistics from EQL.
* Annihilator - player with the most damage (any non-duel game)
* RL Killer - player with the most enemy rl kills (non-duel, dmm1)
* Boomsticker - player with the top sg effi (non-duel, dmm1)
=> Add More Teamplay End Game Statistics

include/progs.h, src/items.c, src/match.c
Detect and log Transferred packs in the end game stats. When a pack drops, record the dropping player / team. When the pack is picked up, if it was within the same team, credit the original player with a transferred pack. Show transferred packs in end game stats if non-zero.
I wasn't sure how best to handle player name / team name nonsense. It seems there are like a dozen different ways to do this and most are unsafe. I copied the team name since getteam() doesn't seem to return a safe value. I use the player's netname since that seems like a pointer unlikely to change. Review comments appreciated.
End game player stats: (shows non-zero Xfers)
End game team stats: (always shows Xfers)
Tested: Player dropped to themselves, player dropping to teammate, player dropping to enemy, player …
=> Detect Transferred Packs - Packs Not Dropped to Enemy

include/progs.h, src/commands.c, src/match.c
When a player adds a demo marker the should see it was added:
End Game should list marks and who made them:
=> Spruce up demo marker output

include/progs.h, src/client.c, src/match.c
For Duel: Include a time / % time player was in control.
Simple heuristic for control right now (start = spree > 2, end = death / game over).
For Team: Include a time per player and per team quad was held.
This could probably be excluded if all players have 0 (e.g. dm4) but so many stats already dump 0 for everyone in most cases that I just left it in.
=> Add End Game Time Stats

include/progs.h, src/combat.c, src/match.c
Chose not to do total team self damage for team stats, but that would be easy to add.
=> Add End Game Self Damage Stat

src/sp_monsters.c
Some wizards which spawn right next to walls/ceilings to be in constant
state of waiting five seconds before trying to spawn again... but during
this time they see player, nextthink is changed accordingly, and the
player is attacked by a wizard that they cannot see or hit.
(example is e1m2 in the secret to the right hand side of the start)
=> SP_MONSTERS: only use is_location_occupied in bloodfest mode

src/race.c
Bounds check leads to off by one error, then race_weapon_mode() calls G_Error
(command only available when /race enabled)
=> RACE: Prevent remote crash through race_show_record_details

src/vote.c
Currently they would have to disconnect and let FixNoSpecs() correct it.
=> NOSPECS: Let player turn nospecs off if they are last player on server

src/weapons.c
Currently if you keep +attack held down and run out of ammo, you will
switch to W_BestWeapon(), which ignores w_switch and b_switch.  This
could lead to the player running out of nails/shells and accidentally
switching back to LG, then dropping the pack.
=> WEAPONS: Add userinfo key w_rank to allow users to rank weapons

include/progs.h, src/combat.c, src/match.c
In dmm1 team games (typically 3on3, 4on4) it may be useful to know how much damage you gave to enemies that were holding weapons. So alongside Damage taken / given show given to enemy weapons (enemies holding RL or LG).
This was requested on [qw.nu forums](http://www.quakeworld.nu/forum/topic/6742/102223/another-feature-request#102223).
Per player stats: (certainly useful)
Per team stats: (less useful, but might as well include it)
=> Add End Game Enemy Weapon Damage Stat

include/g_local.h, include/g_syscalls.h, src/client.c, src/g_syscalls.c, src/g_utils.c, src/maps.c, src/world.c
Any .ent files in the maps or entfiles directories which are in format
mapName#xxx.ent will be added to the maps list.  If selected, uses extended
map command in mvdsv (map <mapname> <entfile>) to switch.
Requires server support for updated map command.
=> ENTITY FILES: Support multiple .ent files for each map.

include/progs.h, src/g_spawn.c, src/race.c
This is to so KTX doesn't need to be updated whenever a new race map
is created.
Two new entity types:
race_route_start
race_route_marker
race_route_start requires the following properties:
origin (vector)
race_route_name (string)
race_route_description (string)
race_route_timeout (int)
race_route_weapon_mode (enum - matches KTX raceWeapoMode_t)
race_route_falsestart_mode (enum - matches KTX raceFalseStartMode_t)
target (string, must point to corresponding race_route_marker)
race_route_marker requires:
origin (vector)
targetname (string)
Each entity links to next marker through target attribute, the last marker
in the sequence is considered the end of the route.
=> RACE: Allow race routes to be defined by map entities

src/vote.c
A few players mentioned this on the [quakeworld.nu forums](http://www.quakeworld.nu/forum/topic/6688/101856/qw-tweaks-and-ideas-brainstorm/#101856). So here is a fix.
=> Ending a game with break should show stats and save demo

meson.build, meson_options.txt
You can now enable/disable bot support via the "bot_support" option. It is enabled by default.
=> MESON: add meson_options.txt

resources/example-configs/ktx/ktx.cfg, src/bot_aim.c, src/bot_botstat.c, src/bot_botweap.c, src/client.c, src/combat.c, src/grapple.c, src/runes.c, src/weapons.c, src/world.c
New cvars allow one to modify independently each rune power level in CTF:
- k_ctf_rune_power_str (Strength), 
- k_ctf_rune_power_res (Resistance),
- k_ctf_rune_power_rgn (Regeneration),
- k_ctf_rune_power_hst (Haste).
Default value is 2, as it has always been (previously hardcoded).
=> CTF: Runes power settings

include/g_consts.h, src/ctf.c
CTF sounds such as flag taken, flag capture etc. are currently sharing
the 'VOICE' channel. This has the effect of flag related sounds being
overriden by common sounds such as player landing, hit sounds, pain
sounds etc.
During a busy game this can effectively mute flag sounds which are
important events during a CTF match.
This change places flag related sounds on their own channel.
=> CTF: Make flag sounds play on own independant channel

src/g_main.c, src/maps.c
Stay in mapcycle even when voted map exists in cycle.  Show proper mapcycle number when warning about min/max player requirements not being met.
=> MAPCYCLE fixes - minor

include/g_local.h, include/progs.h, resources/example-configs/ktx/configs/usermodes/matchless/ctf.cfg, src/commands.c, src/ctf.c, src/g_utils.c, src/grapple.c, src/player.c, src/world.c
I've been playing some **KTX CTF** recently, and noticed that the hook didn't feel quite right compared with the original 3wave implementation.  This PR introduces a few improvements:
hook throw/pull and tracking have hardcoded 100ms updates.  This can get out of sync with the server's ticrate, and causes noticeable choppiness & "jitter" issues
* sync hook throw/pull/track updates to server ticrate using `next_frame()` util [`time + frametime`]
* remove gravity hack (previous attempt at mitigating hook issues?)
While grappling, the weapon animation flickers back & forth between `weaponframe 3` and `weaponframe 4`
* fix weaponframe calls in `player_chain` functions in `player.c`
* sync `player_chain` func calls w/ server ticrate using `next_frame()` util [`time + frametime`]
The hook and …
=> CTF | grappling hook improvements, alternate grapple velocities

src/admin.c, src/match.c
This PR tackles 2 things from #127:
- when a player became an elected admin, all his previous votes are invalidated
- an elected admin loses his admin rights when the match starts
These changes were done by @meag in his fork. I just copy+pasted it into my fork, and made the PR.
=> Elected admin tweaks

src/match.c
reverted: elected admins lose rights when match starts
=> Elected admin tweaks (#127): reverted: elected admins lose rights when match starts

include/g_local.h, src/admin.c, src/commands.c, src/vote.c
A map vote from an admin will no longer bypass the percentage system
and force the map to change. It will be treated like a regular vote
instead.
If the need to force a change of map arises, there is a new command,
forcemap <mapname>, which does precisely that.
Only admins can execute forcemap, and it will refuse to work if a match
is currently in progress (admins can forcebreak the match first if
necessary).
=> Improved map voting mechanics for admins.

src/commands.c
The /gamemodes command prints a list of game modes available on the
server.
It does this by maintaining a list of a known modes and searching
through the command list to see which are available.
=> Added /gamemodes command.

resources/example-configs/ktx/ktx.cfg
Update format according to the comment on the same line. The current invalid timestamp format results in ambiguous timestamps.
=> Fix value of variable k_demoname_date

src/g_utils.c
QE does not like multicast centerprint.
FTE does not like it either (for mvd demo recording).
=> QE: fix match start crash

src/g_utils.c, src/world.c
k_no_scoreboard_ghosts toggles ghosts (fake players during disconnect) for scoreboard.
Ghosts cause disconnects for QE so disabling them is a workaround.
=> QE: add k_no_scoreboard_ghosts cvar

CMakeLists.txt, tools/q3asm/CMakeLists.txt, tools/q3lcc/CMakeLists.txt
Unlocks optional longer compile times. cmake 3.9.0 was released Nov 30, 2018, so far from bleeding edge - CI is on 3.10.2.
```
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=1 ..
```
Previous output:
```
CMake Warning (dev) at CMakeLists.txt:130 (add_library):
Policy CMP0069 is not set: INTERPROCEDURAL_OPTIMIZATION is enforced when
enabled.  Run "cmake --help-policy CMP0069" for policy details.  Use the
cmake_policy command to set the policy and suppress this warning.
INTERPROCEDURAL_OPTIMIZATION property will be ignored for target 'qwprogs'.
This warning is for project developers.  Use -Wno-dev to suppress it.
```
=> BUILD: Bump cmake req to 3.9.0 to allow LTO.

src/client.c, src/g_spawn.c, src/runes.c
This introduces k_ctf_based_spawn 2 which utilizes three types of
spawn points.
1. info_player_deathmatch
Neutral territory, typically mid section of map.
2. info_player_team(1|2)
Start position, typically a balanced distance to powerups. A very
poor match for deathmatch spawns if enemy is in your base with quad
and strength and you respawn in pretty much the same place every time.
3. info_player_team(1|2)_deathmatch
Additional spawn positions that would be offensive for the opposing
team to spawn at during game, typically within your home base.
At start, it works as regular CTF spawns, but once match has started and
a player is respawned the selection has a 50/50 chance of spawning at a
neutral spawn point or at a spawn point within your home base.
Runes will like the traditional mode …
=> CTF: Add a more flexible version of CTF based spawn.

src/g_spawn.c, src/runes.c
More than once there has been discussions on rune spawns and how they
randomly might give one of the teams an upper hand.
This feature gives mappers the ability to integrate rune spawn positions
into the map design that will be used whenever a rune (re)spawns.
Dropping a rune still drops it on the ground, but if not picked up, the
regular timeout will cause the rune to respawn at a dedicated position if
such a position is available.
=> RUNES: Let mappers dictate rune spawns.

src/triggers.c, src/world.c
When k_ctf_hurt_items is enabled both flags and runes will instantly
respawn when touching a trigger_hurt.
The use case is open maps where such items may fall into the void and
you don't want to wait for the rune and flag timeouts.
=> CTF: Add support for destroying flags and runes.

src/runes.c
Setting any of the existing `k_ctf_rune_power_*` to `0` prevents spawning of this rune.
=> CTF: Make it possible to disable individual runes.

src/clan_arena.c
When compiling with -Werror=format-security the compiler will error out at these function calls. This PR fixes #249.
My C skills are very rusty, I had a look at https://fedoraproject.org/wiki/Format-Security-FAQ and fixed those function calls based on my poor understanding of function definition of G_centerprint.
It fixes the compilation error, but I have not verified if it still behaves the same in game, as I'm unsure where/when it gets called and how to trigger that.
=> Fix format string vulnerabilities (Fixes: #249)

src/stats.c
- Quadruns in the top performer section should be omitted if it is 0 (meaning that there is no Q in the game just played).
- In top performers table a % missing after efficiency
- New stat table: dmg per weapon
=> Some fine tunings on the Endgame Stats

src/runes.c, src/world.c
Runes spawn at either designated `item_rune_$name` spawn points, or `info_player_deathmatch`, and usually there aren't that many to pick from which results in a fairly high probability that multiple runes spawn at the same spawn point, and worst case this spawn point is on the way between base and quad at map start.
This PR introduces unique spawn point selection at match start for runes, and secondly also ports the PureCTF functionality of bouncing runes which further improves the randomization by causing runes to sometimes bounce down ledges etc.
=> RUNES: Randomized rune spawns.

src/runes.c
The rune spawn randomization incorrectly made runes bounce when player holding a rune died as the death of a player and fresh rune respawn uses the same function. This diverges from PureCTF and negatively impacts gameplay. This was gameplay tested before merge, but nobody took notice of it in time.
=> RUNES: Don't bounce if released from dead player.

src/client.c, src/world.c
Currently, players have to individually request this info via the /klist command. That sucks. This change allows us to create cool hud elements to see this info in real time, alert players when specs are following them, and other fun stuff.
=> Send spectator info to clients

CMakeLists.txt, include/progs.h, include/q_shared.h, src/func_bob.c, src/func_laser.c, src/g_spawn.c, src/g_syscalls.c, src/hiprot.c, src/misc.c, src/triggers.c
This brings along the complete set of entities used in the RCTF maps by infiniti. All of them widely available and used in the SP mapping community, nothing too fringe. Should be lots of room in mvdsv for a more bloated edict now with the lean bsp loading in place.
Intend to put together a FGD (TrenchBroom description file) in a separate repository to document these entities together with the existing ktx custom entities so it's easier for mappers to target ktx.
TL;DR:
* ambient_general - like the other ambient_* but with custom wav.
* func_bob - smooth bobbing model, can't really be done with func_train.
* func_laser - a forcefield door-like entity with pulsating alpha value that can damage player on touch.
* hiprot - func_rotate etc, from Scourge of Armagon mission pack, hated but …
=> Additional ents

src/commands.c, src/items.c, src/match.c, src/world.c
/fresh enables FreshTeams (faster weapon spawns, less ammo) 
/freshpacks toggles pack ammo limits in FreshTeams 
/freshguns toggles weapon sweep ammo limits in FreshTeams 
/freshtime toggles weapon spawn times between 20/15/10 seconds (20 is default) 
/nosweep disables weapon sweeping in dmm1 (does not require FreshTeams)
=> FRESHTEAMS: new dmm1 variation

include/g_local.h, include/progs.h, src/commands.c, src/grapple.c, src/vote.c
Added crhook hookstyle as described by @inf1niti in #303 
At the moment, haste still affects throw speed when using crhook, as that was the original behaviour crhook was removed. I also changed the naming of the speed constants, since the speed for the new hook styles was called CR_THROW_SPEED.
=> Added crhook hook style

CMakeLists.txt
MacOS linker has different flags than gcc.
=> BUILD: fix macos build

include/g_local.h, src/commands.c, src/race.c, src/world.c
=> race: commands to change and vote countdown(vvd)

src/clan_arena.c, src/combat.c
- Fixed a bug that causes dead players to take damage in certain situations
- Spawning players cannot be bounced by rockets/grenades
- Tell the client who dead players are tracking (for better demo playback)
=> CA/WIPEOUT: bug fixes and improvements

src/vote.c
It would be nice to keep the new functionality but revert the team names back to red/blue and 'yell' in modes where a third team is necessary. Not sure if this is what you want to do but I figured it would save time since the work has already been done.
=> RPICKUP: change team names back to red/blue

src/func_bob.c
Support for non-solid func_bob has not yet been implemented. Best to remove them for now to avoid blocking players on maps that do use them.
Partial fix for #330
=> Remove non-solid func_bob entities.

src/commands.c
The `lastscores` command in KTX conflicts with the `lastscores` command in mvdsv. Therefore, when calling `cmd lastscores` you'll invoke the mvdsv command instead of the KTX command, as one might expect.
=> Add alias of lastscores as lastscoresktx

src/clan_arena.c, src/combat.c, src/g_userinfo.c
Various wipeout related updates:
- Simplified "1on1" notifications
- Spawning players cannot take or give damage for 1 second (but can still rocket jump)
- Respawn times are now calculated based on  number of players in team. This should improve 2v3 or 3v4 experience.
- Some minor bug fixes with sounds and team settings
=> Wipeout updates

include/g_local.h, src/commands.c, src/world.c
Add 3 second centerprint countdown before pauses and unpauses
Also added switch sound effect during pause countdown
=> PAUSE: countdown warning for pause/unpause

src/g_utils.c
The function `g_random`, which
- normalizes the output of the underlying PRNG to the range [0,1)
- is the basis of all random calls in the game
performs sub-optimally because it utilizes the poorest performing bits (in terms of randomness) from the PRNG; namely, the lower bits.
Use the upper bits instead.
They perform much better. The designers of the PRNG say so, and the following benchmarks agree.
Each output from the PRNG is 32 bits wide.
The [ENT — Fourmilab Random Sequence Tester](https://github.com/Fourmilab/ent_random_sequence_tester) was used to quickly compare the random qualities of 3 MB of data generated using
1. All 32 bits; the ideal, but not possible in-game without loss of precision or switching to double everywhere.
2. The lower 15 bits; the current implementation.
3. The …
=> fix rng normalization

CMakeLists.txt
Much cleaner msvc CI output with potentially actionable warnings.
=> WIN: Disable some opinionated msvc warnings.

src/items.c
nquake-sv has a comment that mentions values 0,1,2 to select model, and the original mapping was 0 and >0, this makes the new selection compatible with that and doesn't break existing configs.
=> SPAWN: Better k_spm_custom_model compatibility.

src/commands.c
/handicap and /dmgfrags commands in LGC mode give ability to get more frags than wihtout these commands. Some guys used it in that table https://badplace.eu/map/povdmm4/arena . This PR prevents enabling of these commands in LGC mode
=> Prevent handicap and dmgfrags changing in LGC mode

src/match.c
Players are assigned the first available spot in the svs.clients array when they connect to a mvdsv server. On an empty server, this means that player1 is placed at svs.clients[0], player2 at svs.clients[1], and so on.
KTX iterates over svs.clients at the start of a match to decide where each player will spawn. This becomes problematic when there are fewer spawn points than players. A good example is dm3, which only has six spawns.
In the scenario where players connect to an empty server, they occupy the indexes 0 through 7 in the svs.clients array and are processed in this predictable order. This means player1 gets a random spawn before player2, player2 before player3, and so forth.
When it reaches player7, all spawn points are occupied. A random spawn is selected, and the player at that …
=> Randomize the processing order of the initial spawn

src/race.c
Introduced back in 2011 via 9fc1a31 but hidden thanks to strlcpy incorrectly using source buffer length (and risking buffer overflow). After fe38404 strlcpy was invoked with destination buffer length, and source buffer was copied up until NUL-termination and thus incorrectly included the \n.
Found by @VVD, fixes #388
=> RACE: Trim trailing \n when reading top scores.

include/g_local.h, src/client.c, src/commands.c, src/g_utils.c
In 2012, commit 3043a91 imported phil's hoonymod into KTX, changing normal QW respawns from being randomized to cycling through the list of spawns in a predetermined order.
From what I can tell, hoonymod no longer even uses k_spw 0. However, just in case, I've added k_spw -1, which allows the use of non-randomized spawns if anyone ever wants that again.
=> Fix Normal QW respawns

include/progs.h, src/bot_botimp.c, src/bot_botjump.c
This PR adjust the lower thresholds of the bot skill levels with regards to aim, movement and reaction time.
* Skill 1 bots are now cannonfodder (so they are more suitable for someone completely new to the game).
* Bots only rocketjumps above skill 5. 
* Skill 20 should still be the same since i haven't touched the upper thresholds.
* LGC mode generally uses skill 10 however, so i kept the old settings for LGC mode to still be able to play that on same terms as before.
// Åke Vader
=> Adjust lower bot skill thresholds

resources/example-configs/ktx/bots/maps/schloss.bot
A couple fixes to bot waypoints on Schloss:
- Bots often got stuck by health packs in tower when going to RL (moved the waypoint closer to the stairs).
- Bots often got stuck by the spiral stair window. They'll still go for the window now but hopefully with a higher success rate (new waypoint just below the window, and made it one way).
=> Fix bot waypoint issues on schloss

include/progs.h, src/client.c, src/combat.c, src/commands.c, src/match.c, src/triggers.c, src/weapons.c
Some players like to use prewar to practice movement or trick jumps and don't want to be bothered by other players shooting around. /leavemealone prevents your player from being knocked around by other players' fire.
=> LEAVEMEALONE: players can't bother you in prewar

CMakeLists.txt, tools/q3asm/CMakeLists.txt
Compatibility with CMake < 3.10 will be removed from a future version of CMake. Updating the min version in advance.
=> Update cmake min version requirement to 3.10
